#!/bin/bash
set -e 

patches_dir=~/solaris8u7git/onbox/patches

overwrite=no
if [ "$1" == "-f" ]; then
	overwrite=yes
	shift
fi

toss_args=""
if [ "$1" == "--allow-makefile" ]; then
	toss_args="$1"
	shift
fi

if [ $# -ne 1 ]; then
	echo "Usage:"
	echo "$0 [-f] [--allow-makefile] {dirname}"
	exit 1
fi

set -x
dirname="$1"
origdirname="${dirname}.orig"
outputfile="${patches_dir}/${dirname}.patch"

if [ ! -d "$dirname" ]; then
	echo "$dirname not found"
	exit 1
fi

if [ ! -d "$origdirname" ]; then
	echo "$origdirname not found"
	exit 1
fi

if [ -f "$outputfile" ]; then
	if [ "$overwrite" == "no" ] ; then
		echo "$outputfile already exists"
		exit 1
	else
		cp "$outputfile" "${outputfile}.prev"	
	fi
fi

gdiff --exclude=".deps" --exclude="*.log" -ur "$origdirname" "$dirname" | fgrep -v "Only in $dirname/" > "$outputfile"

"${patches_dir}/toss_patch.py" "$toss_args" "$outputfile"

cat "$outputfile"

