#!/usr/bin/env bash
set -e 

patches_dir=~/solaris8u7git/onbox/patches

overwrite=no
if [ "$1" == "-f" ]; then
	overwrite=yes
	shift
fi

if [ "$1" == "-s" ]; then
	copyups=yes
	shift
else
	copyups=no
fi

if [ $# -lt 1 ]; then
	echo "Usage:"
	echo "$0 [-f] [-s] {dirname} [args for patchout]"
	exit 1
fi

set -x
dirname="$1"
origdirname="${dirname}.orig"
outputfile="${patches_dir}/${dirname}.patch"
shift

if [ ! -d "$dirname" ]; then
	echo "$dirname not found"
	exit 1
fi

if [ ! -d "$origdirname" ]; then
	echo "$origdirname not found"
	exit 1
fi

# checks complete

if [ "$copyups" == "yes" ]; then
	pushd "$dirname"
	for filename in config.h config.status; do
	if [ -f $filename ]; then
		copytoorig $filename
	fi
	done
	popd
fi

if [ "$overwrite" == "no" ] && [ -f "$outputfile" ]; then
	echo "$outputfile already exists"
	exit 1
fi

gdiff --exclude=".deps" --exclude="*.log" -ur "$origdirname" "$dirname" | fgrep -v "Only in $dirname/" > "$outputfile"

"${patches_dir}/toss_patch.py" $* "$outputfile"

cat "$outputfile"

