#!/bin/bash
set -e

if [ $# -lt 1 ]; then
	echo "Usage:" 1>&2
	echo "$0 {install} {packagename}" 1>&2
	exit 1
fi

set -x

command="$1"
shift
packagenames="$*"

case $command in
install)

	sudo pkgutil -i -y $packagenames
	;;
list)
	sudo pkgutil -l
	;;
listfiles)
	sudo pkgutil -L $packagenames
	;;
search)
	sudo pkgutil -a | fgrep $packagenames
	;;
update)
	sudo pkgutil -U
	;;
findfile)
	sudo pkgutil -F "${packagenames}"
	;;
findfilepkg)
	sudo pkgutil -F "${packagenames}" | awk '{print $2}' | sort | uniq
	;;
help)
	set +x
	echo "Usage:"
	echo " pkg install {packagename} 	install a package"
	echo " pkg list				list packages"
	echo " pkg listfiles {x}		list files in package"
	echo " pkg search {x}			look for packages with x in the name"
	echo " pkg update			download updated pkg index"
	echo " pkg help				show this help"
	echo " pkg findfile {x}			find files matching {x} in packages"
	echo " pkg findfilepkg {x}		find a package containing the given file"
	;;

*)
	echo "Unknown command $command" 1>&2
	exit 1
	;;
esac

